-- 계정생성 (dba로 하세용)
CREATE USER dodream IDENTIFIED BY dodream;
GRANT RESOURCE TO dodream;
GRANT CONNECT TO dodream;


-- 테이블 생성 (dodream으로)
DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
   "USER_NO"   NUMBER      NOT NULL,
   "USER_EMAIL"   VARCHAR2(60)      NOT NULL,
   "USER_NICKNAME"   VARCHAR2(100)      NOT NULL,
   "USER_PWD"   VARCHAR2(100)      NOT NULL,
   "USER_EMAILAUTH_YN"   VARCHAR2(1)   DEFAULT 'N'   NOT NULL,
   "USER_ADMIN_YN"   VARCHAR2(1)   DEFAULT 'N'   NOT NULL,
   "USER_STATUS"   VARCHAR2(1)   DEFAULT 'Y'   NOT NULL,
   "USER_ENROLL_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "USER_UPDATE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL
);

COMMENT ON COLUMN "MEMBER"."USER_NO" IS 'SEQ_MNO';

COMMENT ON COLUMN "MEMBER"."USER_EMAILAUTH_YN" IS '이메일인증시 'Y'';

COMMENT ON COLUMN "MEMBER"."USER_ADMIN_YN" IS '일반회원 'N'';

COMMENT ON COLUMN "MEMBER"."USER_STATUS" IS '탈퇴시 'N'';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
   "USER_NO"
);

CREATE SEQUENCE SEQ_MNO;

INSERT INTO MEMBER VALUES(
SEQ_MNO.NEXTVAL,
'test@test.com',
'테스트닉네임',
'asd123',
DEFAULT,
DEFAULT,
DEFAULT,
SYSDATE,
SYSDATE
);

COMMIT;