--------------------------------------------------------------
------ RESERVE 용

INSERT INTO RESERVE VALUES (
    SEQ_RES_NO.NEXTVAL, 'testBillingKey', 1000, TO_DATE('2019-09-23 12:00:00','YYYY-MM-DD HH24:MI:SS'), 
    '배송이름', '01000000000', '01010,서울시 중구,다동', '이렇게저렇게 해주세요', 24, 54
);

INSERT INTO RESERVE VALUES (
    SEQ_RES_NO.NEXTVAL, 'testBillingKey2', 50000, TO_DATE('2019-09-23 12:00:00','YYYY-MM-DD HH24:MI:SS'), 
    '배송이름2', '01000000002', '01010,서울시 중구,다동', '이렇게저렇게 해주세요', 25, 54
);

INSERT INTO RESERVE VALUES (
    SEQ_RES_NO.NEXTVAL, 'testBillingKey3', 50000, TO_DATE('2019-09-23 12:00:00','YYYY-MM-DD HH24:MI:SS'), 
    '배송이름2', '01000000002', '01010,서울시 중구,다동', '이렇게저렇게 해주세요', 25, 54
);

COMMIT;

-- HISTORY 테이블에도 추가
INSERT INTO HISTORY VALUES (
    3, 2, 1
);


--각 예약 번호별 리워드 금액 합계 조회하는 뷰
CREATE OR REPLACE VIEW RES_SUM AS
SELECT RESERVE_NO, SUM(REWARD_PRICE) AS REWARD_PRICE_SUM FROM HISTORY
JOIN REWARD USING ( REWARD_NO )
GROUP BY RESERVE_NO
;

SELECT * FROM RES_SUM;

-- RESERVE 테이블 + 각 결제 별 금액 합계 같이 조회 해보기 + 추가 후원금까지 같이 출력
CREATE OR REPLACE VIEW RESERVE_VIEW AS
SELECT R.* , S.REWARD_PRICE_SUM, R.ADDITIONAL+S.REWARD_PRICE_SUM AS TOTAL
FROM RESERVE R
JOIN RES_SUM S ON (R.RESERVE_NO=S.RESERVE_NO);

SELECT * FROM RESERVE_VIEW;

-- 각 프로젝트별 결제금액을 같이 프린트 해볼까?
-- 왜 이렇게 한번에 잘 되는거야 나는 천재인가
CREATE OR REPLACE VIEW PROJECT_LIST_VIEW AS
SELECT P.*, C.PROJECT_CT_NAME, FLOOR(PROJECT_CLOSE_DT - SYSDATE) AS D_DAY, NVL((SELECT SUM(TOTAL) FROM RESERVE_VIEW V WHERE V.RESERVE_REF_PNO = P.PROJECT_NO GROUP BY RESERVE_REF_PNO),0) AS TOTAL
FROM PROJECT_TB P
JOIN PROJECT_CG C ON ( P.PROJECT_CT_NO = C.PROJECT_CT_NO )
WHERE PROJECT_ST_NO IN ( 4, 5 )
ORDER BY PROJECT_COUNT DESC, PROJECT_CLOSE_DT DESC;

SELECT * FROM PROJECT_LIST_VIEW
WHERE PROJECT_NO = 54;
