UPDATE USER_TB SET USER_ADMIN_YN = 'N' WHERE USER_EMAIL LIKE '%test.co.kr';
commit;

SELECT * FROM USER_TB WHERE USER_ADMIN_YN = 'Y';
ALTER TABLE FOLLOW_TB ADD (FOLLOW_DATE DATE DEFAULT SYSDATE);
ALTER TABLE FOLLOW_TB ADD (FOLLOWER_DATE DATE DEFAULT SYSDATE);

SELECT * FROM FOLLOW_TB;

ROLLBACK;

COMMIT;

INSERT INTO FOLLOW_TB VALUES(1, 2, SYSDATE, SYSDATE);
INSERT INTO FOLLOW_TB VALUES(2, 1, SYSDATE, SYSDATE);
INSERT INTO FOLLOW_TB VALUES(1, 3, SYSDATE, SYSDATE);

--테스트data 100
BEGIN
    FOR I IN 1..100
    LOOP 
    INSERT INTO FOLLOW_TB VALUES(110, I, SYSDATE, SYSDATE);
    END LOOP;
    END;
    /
    
COMMIT;

SELECT * FROM FOLLOW_TB WHERE FOLLOW = '110';

--테스트data 100
BEGIN
    FOR I IN 1..100
    LOOP 
    INSERT INTO FOLLOW_TB VALUES(109, I, SYSDATE, SYSDATE);
    END LOOP;
    END;
    /
    
COMMIT;

SELECT * FROM FOLLOW_TB WHERE FOLLOW = '109';

INSERT INTO FOLLOW_TB VALUES(109, 110, SYSDATE, SYSDATE);
INSERT INTO FOLLOW_TB VALUES(110, 109, SYSDATE, SYSDATE);

INSERT INTO FOLLOW_TB VALUES(23, 110, SYSDATE, SYSDATE);
INSERT INTO FOLLOW_TB VALUES(45, 110, SYSDATE, SYSDATE);
INSERT INTO FOLLOW_TB VALUES(59, 110, SYSDATE, SYSDATE);

COMMIT;

SELECT COUNT(*) FROM FOLLOW_TB WHERE FOLLOW = '110'; --나를 팔로잉한 사람의 수(나의 팔로워)
SELECT COUNT(*) FROM FOLLOW_TB WHERE FOLLOWER = '110';-- 내가 팔로잉한 사람의 수(나의 팔로잉)

SELECT COUNT(*) FROM FOLLOW_TB JOIN USER_TB ON(USER_NO = FOLLOW) WHERE FOLLOW = '110';

-- view생성
CREATE OR REPLACE VIEW FOLLOWERLIST AS 
SELECT FOLLOW, FOLLOWER, USER_NICKNAME, USER_PF_IMG, USER_SELF, FOLLOW_DATE, (SELECT COUNT(*) FROM PROJECT_TB WHERE PROJECT_WRITER = FOLLOW ) AS "OPEN_PROJECT" FROM FOLLOW_TB 
JOIN USER_TB ON(FOLLOW = USER_NO);-- 내가 팔로잉한 사람

SELECT F.*, (SELECT COUNT(*) FROM PROJECT_TB WHERE PROJECT_WRITER = F.FOLLOW ) AS "OPEN_PROJECT" 
FROM FOLLOW_TB F
WHERE FOLLOWER = 110;

select * from FOLLOWERLIST where follower = 110;


CREATE OR REPLACE VIEW FOLLOWLIST AS SELECT FOLLOW, FOLLOWER, USER_NICKNAME, USER_PF_IMG, USER_SELF, FOLLOWER_DATE FROM FOLLOW_TB JOIN USER_TB ON(FOLLOWER = USER_NO);-- 나를 팔로잉한 사람 

SELECT * FROM FOLLOWERLIST WHERE FOLLOWER = '110'; --나의 팔로잉
SELECT * FROM FOLLOWLIST WHERE FOLLOW = '110'; -- 나의 팔로워

SELECT FOLLOW, USER_NICKNAME, USER_SELF, USER_PF_IMG FROM FOLLOW_TB JOIN USER_TB ON(FOLLOW = USER_NO) WHERE FOLLOWER = '110'; -- 내가 팔로잉한 사람
SELECT FOLLOWER, USER_NICKNAME, USER_SELF, USER_PF_IMG FROM FOLLOW_TB JOIN USER_TB ON(FOLLOWER = USER_NO) WHERE FOLLOW = '110';-- 나를 팔로잉한 한사람

SELECT * FROM USER_TB WHERE USER_EMAIL = 'sourcandy120@gmail.com';

SELECT * FROM PROJECT_TB;

SELECT * FROM FOLLOWLIST WHERE FOLLOW = 110;

SELECT * FROM USER_TB;

SELECT * FROM FOLLOWLIST WHERE FOLLOW = '110' ORDER BY FOLLOWER_DATE DESC;
SELECT * FROM FOLLOWERLIST WHERE FOLLOWER = '110' ORDER BY FOLLOW_DATE DESC;


--회원탈퇴
-- 프로젝트 오픈(펀딩중 4, 펀딩마감 5)
SELECT COUNT(*) FROM PROJECT_TB JOIN USER_TB ON(USER_NO = PROJECT_WRITER) WHERE PROJECT_WRITER= '59' AND PROJECT_ST_NO ='4' OR PROJECT_ST_NO ='5';
-- 조회결과있으면 버튼을 disabled처리

-- 내가 펀딩한 프로젝트 중 RESERVE_ST_NO 1인것 (결제대기) 
SELECT COUNT(*) FROM RESERVE WHERE RESERVE_STATUS_NO = '1' AND RESERVE_USER = 30;
-- -> 결제취소 3으로 업데이트
UPDATE RESERVE SET RESERVE_STATUS_NO = '3' WHERE RESERVE_USER = 30;

-- 결재 완료한 프로젝트 갯수(알려주기) ->배송지 변경 불가 alert
SELECT COUNT(*) FROM RESERVE WHERE RESERVE_STATUS_NO = 2 AND RESERVE_USER = 30;


-- 탈퇴회원 결제 취소 trigger생성
UPDATE USER_TB SET USER_STATUS = 'Y' WHERE USER_NO = 66;
commit;
SELECT * FROM USER_TB WHERE USER_NO = 66;


--ALTER TABLE 테이블명 DROP COLUMN 컬럼명
-- 자동로그인 관련 컬럼 삭제
ALTER TABLE USER_TB DROP COLUMN AUTO_SESSIONKEY;
ALTER TABLE USER_TB DROP COLUMN AUTO_EXPIRYDATE;

COMMIT;
--아티스트 페이지 출력
SELECT * FROM USER_TB JOIN PROJECT_TB ON (USER_NO = PROJECT_WRITER) WHERE PROJECT_WRITER = 15;

--마이페이지 내가 펀딩한 리스트 출력
SELECT * FROM PROJECT_TB WHERE PROJECT_NO
IN(SELECT DISTINCT(RESERVE_REF_PNO) FROM RESERVE WHERE RESERVE_USER = 3);

SELECT RESERVE_REF_PNO FROM RESERVE WHERE RESERVE_USER = 3;

SELECT * FROM PROJECT_LIST_VIEW WHERE PROJECT_NO
IN(SELECT DISTINCT(RESERVE_REF_PNO) FROM RESERVE WHERE RESERVE_USER = 3);

-- 내가 오픈한 프로젝트 리스트
SELECT * FROM PROJECT_MYLIST_VIEW JOIN USER_TB ON(USER_NO = PROJECT_WRITER) WHERE PROJECT_WRITER= 79 AND PROJECT_ST_NO IN(1,2,3,4,5,6,7);

SELECT * FROM PROJECT_MYLIST_VIEW WHERE PROJECT_ST_NO = 1;

-- view
CREATE OR REPLACE FORCE VIEW "DODREAM"."PROJECT_MYLIST_VIEW" ("PROJECT_NO", "PROJECT_TITLE", "PROJECT_STITLE", "PROJECT_GOAL", "PROJECT_THUMB_IMG", "PROJECT_START_DT", "PROJECT_CLOSE_DT", "PROJECT_HASHTAG", "PROJECT_MAIN_IMG", "PROJECT_SUMMARY", "PROJECT_STORY", "PROJECT_AT_NM", "PROJECT_AT_PF", "PROJECT_AT_SNS1", "PROJECT_AT_SNS2", "PROJECT_AT_CONT", "PROJECT_AT_EM", "PROJECT_ER_DT", "PROJECT_MF_DT", "PROJECT_WRITER", "PROJECT_CT_NO", "PROJECT_ST_NO", "PROJECT_COUNT", "PROJECT_AT_INT", "PROJECT_CT_NAME", "D_DAY", "TOTAL", "COUNTCOUNT", "SUPPORT_COUNT") AS 
SELECT P."PROJECT_NO",P."PROJECT_TITLE",P."PROJECT_STITLE",P."PROJECT_GOAL",P."PROJECT_THUMB_IMG",P."PROJECT_START_DT",P."PROJECT_CLOSE_DT",P."PROJECT_HASHTAG",P."PROJECT_MAIN_IMG",P."PROJECT_SUMMARY",P."PROJECT_STORY",P."PROJECT_AT_NM",P."PROJECT_AT_PF",P."PROJECT_AT_SNS1",P."PROJECT_AT_SNS2",P."PROJECT_AT_CONT",P."PROJECT_AT_EM",P."PROJECT_ER_DT",P."PROJECT_MF_DT",P."PROJECT_WRITER",P."PROJECT_CT_NO",P."PROJECT_ST_NO",P."PROJECT_COUNT",P."PROJECT_AT_INT", C.PROJECT_CT_NAME, FLOOR(PROJECT_CLOSE_DT - SYSDATE) AS D_DAY, NVL((SELECT SUM(TOTAL) FROM RESERVE_VIEW V WHERE V.RESERVE_REF_PNO = P.PROJECT_NO GROUP BY RESERVE_REF_PNO),0) AS TOTAL, (CASE WHEN PROJECT_CLOSE_DT < SYSDATE THEN NULL ELSE PROJECT_COUNT END) AS COUNTCOUNT, (SELECT COUNT(DISTINCT(HIS.RESERVE_NO)) FROM HISTORY HIS JOIN RESERVE RES ON ( HIS.RESERVE_NO = RES.RESERVE_NO ) WHERE RES.RESERVE_REF_PNO = P.PROJECT_NO ) AS SUPPORT_COUNT
FROM PROJECT_TB P
JOIN PROJECT_CG C ON ( P.PROJECT_CT_NO = C.PROJECT_CT_NO )
WHERE PROJECT_ST_NO IN (1,2,3, 4, 5, 7 )
ORDER BY COUNTCOUNT DESC NULLS LAST;

--좋아요한 프로젝트
SELECT * FROM LIKE_TB;
SELECT * FROM LIKE_TB JOIN USER_TB ON(LIKE_USER = USER_NO) JOIN PROJECT_LIST_VIEW ON(LIKE_PRJ = PROJECT_NO) WHERE LIKE_USER = 110;

SELECT * FROM PROJECT_MYLIST_VIEW;

SELECT * FROM USER_TB WHERE USER_EMAIL = 'sourcandy120@gmail.com';

-- 나의 신고내역
SELECT * FROM REPORT_TB JOIN USER_TB ON (REPORT_WRITER = USER_NO) JOIN PROJECT_TB ON (REPORT_REF_PNO = PROJECT_NO) WHERE REPORT_WRITER = 115;

-- 나의 신고 답변확인
SELECT * FROM REPORT_REPLY JOIN REPORT_TB ON (REPORT_RP_REF_RNO = REPORT_NO) JOIN USER_TB ON (REPORT_WRITER = USER_NO) WHERE REPORT_WRITER = 115;

SELECT * FROM REPORT_TB JOIN REPORT_REPLY ON (REPORT_NO = REPORT_RP_REF_RNO) JOIN USER_TB ON (REPORT_WRITER = USER_NO) WHERE REPORT_WRITER = 115;

-- 나의 신고내역+신고답변내역
		SELECT * FROM REPORT_TB
		JOIN REPORT_REPLY ON (REPORT_NO = REPORT_RP_REF_RNO)
		JOIN USER_TB ON (REPORT_WRITER = USER_NO)
        JOIN PROJECT_TB ON (REPORT_REF_PNO = PROJECT_NO)
		WHERE REPORT_WRITER = 115;


SELECT * FROM FOLLOW_TB JOIN USER_TB ON(USER_NO = FOLLOW) WHERE USER_NICKNAME = '테스트유저21'; 

--follow삭제
--DELETE FROM FOLLOW_TB WHERE follow = AND FOLLOWER = 

--아티스트 정보 조회
SELECT * FROM USER_TB JOIN PROJECT_TB ON(PROJECT_WRITER = USER_NO) WHERE USER_NO = '5';






