UPDATE USER_TB SET USER_ADMIN_YN = 'N' WHERE USER_EMAIL LIKE '%test.co.kr';
commit;

SELECT * FROM USER_TB WHERE USER_ADMIN_YN = 'Y';
ALTER TABLE FOLLOW_TB ADD (FOLLOW_DATE DATE DEFAULT SYSDATE);
ALTER TABLE FOLLOW_TB ADD (FOLLOWER_DATE DATE DEFAULT SYSDATE);

SELECT * FROM FOLLOW_TB;

ROLLBACK;

COMMIT;

INSERT INTO FOLLOW_TB VALUES(1, 2, SYSDATE, SYSDATE);
INSERT INTO FOLLOW_TB VALUES(2, 1, SYSDATE, SYSDATE);
INSERT INTO FOLLOW_TB VALUES(1, 3, SYSDATE, SYSDATE);

--테스트data 100
BEGIN
    FOR I IN 1..100
    LOOP 
    INSERT INTO FOLLOW_TB VALUES(110, I, SYSDATE, SYSDATE);
    END LOOP;
    END;
    /
    
COMMIT;

SELECT * FROM FOLLOW_TB WHERE FOLLOW = '110';

--테스트data 100
BEGIN
    FOR I IN 1..100
    LOOP 
    INSERT INTO FOLLOW_TB VALUES(109, I, SYSDATE, SYSDATE);
    END LOOP;
    END;
    /
    
COMMIT;

SELECT * FROM FOLLOW_TB WHERE FOLLOW = '109';

INSERT INTO FOLLOW_TB VALUES(109, 110, SYSDATE, SYSDATE);
INSERT INTO FOLLOW_TB VALUES(110, 109, SYSDATE, SYSDATE);

INSERT INTO FOLLOW_TB VALUES(23, 110, SYSDATE, SYSDATE);
INSERT INTO FOLLOW_TB VALUES(45, 110, SYSDATE, SYSDATE);
INSERT INTO FOLLOW_TB VALUES(59, 110, SYSDATE, SYSDATE);

COMMIT;

SELECT COUNT(*) FROM FOLLOW_TB WHERE FOLLOW = '110'; --나를 팔로잉한 사람의 수(나의 팔로워)
SELECT COUNT(*) FROM FOLLOW_TB WHERE FOLLOWER = '110';-- 내가 팔로잉한 사람의 수(나의 팔로잉)

SELECT COUNT(*) FROM FOLLOW_TB JOIN USER_TB ON(USER_NO = FOLLOW) WHERE FOLLOW = '110';

-- view생성
CREATE OR REPLACE VIEW FOLLOWERLIST AS SELECT FOLLOW, FOLLOWER, USER_NICKNAME, USER_PF_IMG, USER_SELF, FOLLOW_DATE FROM FOLLOW_TB JOIN USER_TB ON(FOLLOW = USER_NO);-- 내가 팔로잉한 사람(나의 팔로잉 리스트)
CREATE OR REPLACE VIEW FOLLOWLIST AS SELECT FOLLOW, FOLLOWER, USER_NICKNAME, USER_PF_IMG, USER_SELF, FOLLOWER_DATE FROM FOLLOW_TB JOIN USER_TB ON(FOLLOWER = USER_NO);-- 나를 팔로잉한 사람 (나의 팔로워 리스트)

SELECT * FROM FOLLOWERLIST WHERE FOLLOWER = '110'; --나의 팔로잉
SELECT * FROM FOLLOWLIST WHERE FOLLOW = '110'; -- 나의 팔로워

SELECT FOLLOW, USER_NICKNAME, USER_SELF, USER_PF_IMG FROM FOLLOW_TB JOIN USER_TB ON(FOLLOW = USER_NO) WHERE FOLLOWER = '110'; -- 내가 팔로잉한 사람
SELECT FOLLOWER, USER_NICKNAME, USER_SELF, USER_PF_IMG FROM FOLLOW_TB JOIN USER_TB ON(FOLLOWER = USER_NO) WHERE FOLLOW = '110';-- 나를 팔로잉한 한사람

SELECT * FROM USER_TB WHERE USER_EMAIL = 'sourcandy120@gmail.com';

SELECT * FROM PROJECT_TB;

SELECT * FROM FOLLOWLIST WHERE FOLLOW = 110;

SELECT * FROM USER_TB;

SELECT * FROM FOLLOWLIST WHERE FOLLOW = '110' ORDER BY FOLLOWER_DATE DESC;
SELECT * FROM FOLLOWERLIST WHERE FOLLOWER = '110' ORDER BY FOLLOW_DATE DESC;


--회원탈퇴
-- 프로젝트 오픈(펀딩중 4, 펀딩마감 5)
SELECT PROJECT_NO FROM PROJECT_TB JOIN USER_TB ON(USER_NO = PROJECT_WRITER) WHERE PROJECT_WRITER= '59' AND PROJECT_ST_NO ='4' OR PROJECT_ST_NO ='5';
-- 조회결과있으면 버튼을 disabled처리

-- 내가 펀딩한 프로젝트 중 RESERVE_ST_NO 1인것 (결제대기) 
SELECT * FROM RESERVE WHERE RESERVE_STATUS_NO = '1' AND RESERVE_USER = 30;
-- -> 결제취소 3으로 업데이트
UPDATE RESERVE SET RESERVE_STATUS_NO = '3' WHERE RESERVE_USER = 30;
-- 결재 완료한 프로젝트 갯수(알려주기) ->배송지 변경 불가 alert
SELECT COUNT(*) FROM RESERVE WHERE RESERVE_STATUS_NO = '2'AND RESERVE_USER = 30;

